inputs:
  enable_fib:
    description: "Enable Fibonacci calculation"
    required: true
    default: "true"
  max_threshold:
    description: "Maximum number allowed"
    required: false
    default: "1000"
