name: "FibBot"
description: "Scans Pull Request content for numbers, calculates their Fibonacci numbers, and posts a comment."
author: "chojuninengu"

inputs:
  pr_number:
    description: "The number of the pull request"
    required: true
  enable_fib:
    description: "Enable Fibonacci calculation (true/false)"
    required: true
  max_threshold:
    description: "The maximum number to compute"
    required: true
  github_token:
    description: "GitHub token for API access"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build FibBot
      run: cargo build --release
      shell: bash

    - name: Run FibBot
      run: |
        export PR_NUMBER="${{ inputs.pr_number }}"
        export GITHUB_TOKEN="${{ inputs.github_token }}"
        ./target/release/fibbot "${{ inputs.enable_fib }}" "${{ inputs.max_threshold }}"
      shell: bash
