name: "FibBot"
description: "Scans Pull Request content for numbers, calculates their Fibonacci numbers, and posts a comment."
author: "cho"

inputs:
  enable_fib:
    description: "Enable Fibonacci calculation (true/false)"
    required: true
  max_threshold:
    description: "The maximum number to compute"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.enable_fib }}
    - ${{ inputs.max_threshold }}
