[package]
name = "FibBot"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
regex = "1.10"
openssl = { version = "0.9", optional = true }
