name: "Run FibBot"

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  run-fibbot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker build -t fibbot .

      - name: Run FibBot
        run: |
          docker run \
            -e PR_NUMBER="${{ github.event.pull_request.number }}" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e GITHUB_REPOSITORY="${{ github.repository }}" \
            -e GITHUB_API_URL="https://api.github.com" \
            fibbot
        shell: bash
