name: FibBot Action

on:
  pull_request:
    types: [opened, synchronize, reopened] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker build -t fibbot .

      - name: Run FibBot Docker container
        run: |
          docker run \
            -e INPUT_ENABLE_FIB=true \
            -e INPUT_MAX_THRESHOLD=1000 \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -e GITHUB_API_URL=https://api.github.com \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e PR_NUMBER=${{ github.event.pull_request.number }} \
            fibbot
