name: "FibBot Test"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-fibbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run FibBot in Docker
        run: docker run --rm your-dockerhub-username/fibbot 
