name: "Test FibBot"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Run Cargo Tests
        run: cargo test

  build-and-push:
    runs-on: ubuntu-latest
    needs: test  # Only build if tests pass

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/chojuninengu/fibbot:latest .

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/chojuninengu/fibbot:latest
